/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package naoko

import io.ktor.client.*
import io.ktor.client.engine.cio.*
import io.ktor.client.features.json.*
import io.ktor.client.features.json.serializer.*
import io.ktor.client.request.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

class Library {

    private val client = HttpClient(CIO){
        install(JsonFeature){
            serializer = KotlinxSerializer(
                kotlinx.serialization.json.Json {
                    ignoreUnknownKeys = true
                }
            )
        }
    }

    suspend fun getResult(): String = withContext(Dispatchers.IO){

        //動作確認をするときはi10janのurlを入れる
        val result = client.get<HttpBin>("https://httpbin.org/get")
        return@withContext result.origin
    }
}
